version: '3.8'

services:
  nginx:
    build: ./srcs/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./srcs/nginx/ssl:/etc/nginx/ssl
      - ./srcs/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network

  wordpress:
    build: ./srcs/wordpress
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /home/tgibert/data/wordpress:/var/www/html
    networks:
      - my_network

  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    user: 999:999
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /home/tgibert/data/mariadb:/var/lib/mysql  # Données persistantes de la base de données
      - /run/mysqld:/run/mysqld
    command: sh -c "mkdir -p /run/mysqld && chown mysql:mysql /run/mysqld && mysqld"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge